# Generated by Django 4.1.13 on 2023-11-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_expense', '0003_expense_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='salary',
        ),
    ]
