# Generated by Django 4.1.12 on 2023-11-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_expense', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Other', 'Other'), ('Personal', 'Personal'), ('Utilities', 'Utilities'), ('MedicalCare', 'MedicalCare')], help_text='Category of expense', max_length=20),
        ),
    ]
